name: Build Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: make image
      - uses: actions/docker/login@master
      - name: push
        run: make push

